services:
  tracking-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./tracking-data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_FILE=/app/data/visitor_tracking.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ultravidz-public-secure.entrypoints=https"
      - "traefik.http.routers.ultravidz-public-secure.rule=Host(`api.ultravidz.com`)"
      - "traefik.http.routers.ultravidz-public-secure.middlewares=error-pages-middleware"
      - "traefik.http.routers.ultravidz-public-secure.tls=true"

networks:
  proxy:
    external: true
#volumes:
#  tracking-data:
#  logs: